name: Build on PR and Push
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main # 또는 원하는 브랜치명
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

      - name: Run TypeScript Check and Build
        run: pnpm run build
